# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0ce0da776da8bdf6994526d1d8746054f8b6fc3acbf9308248950c657a1b489b96bf3cf1e39d094445040b9a00f3e94673fa4384cb4872c9b4f2c2b619f0a8f

test:
  secret_key_base: e94ed03af835ad5f88447b12b6cab6b2ecd6df5acb182a82e1174e7b1bc1e865c7bb9ef219de639f8ae18a554c5faf5f4191b16f03466d1591d66b784942bbb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
